#! sh

# Xmodmap
# -----------------------------------
xmodmap $HOME/.Xmodmap

# Xresource
# -----------------------------------
[[ -f $HOME/.Xresources ]] && {
  /usr/bin/xrdb -merge -I$HOME ~/.Xresources
}

# IME
# -----------------------------------
USE_IM=fcitx
export GTK_IM_MODULE=${USE_IM}
export QT_IM_MODULE=${USE_IM}
export XMODIFIERS="@im=${USE_IM}"
export DefaultIMModule=${USE_IM}

gsettings \
  set \
    org.gnome.settings-daemon.plugins.xsettings \
    overrides \
    "{'Gtk/IMModule':<'${USE_IM}'>}"

# Xprofile local
# ----------------------------------
[[ -f $HOME/.xprofile.local ]] && {
  source ~/.xprofile.local
}
