#! zsh
#
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Main
# ------------------------------------------
### Added by Zplugin's installer
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zplugin installer's chunk
source ${HOME}/.dotfiles/zsh/zinit-conf.zsh

# Configure
# -----------------------------
ZSH_CONFIG_ROOT="${HOME}/.dotfiles/zsh/conf.d"
ZSH_INCLDE_CONF=(
  # base
  alias
  completion
  incremental
  python
  ruby
  perl
  node
  ssh
  golang
  envtool
  secret
)

# Function
# -------------------------------------
function __check_exist_and_source() {

  local target=$1
  [[ -f ${target} ]] && source ${target}

}

for conf in ${ZSH_INCLDE_CONF} ; do
  __check_exist_and_source ${ZSH_CONFIG_ROOT}/${conf}.zsh
done

# export PATH="$HOME/.sc/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/laughk/.local/src/google-cloud-sdk/path.zsh.inc' ]; then source '/home/laughk/.local/src/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
 if [ -f '/home/laughk/.local/src/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/laughk/.local/src/google-cloud-sdk/completion.zsh.inc'; fi


# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk
eval "$(/Users/iwasaki/.local/bin/mise activate zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
