#! zsh

# Configure
# -----------------------------
ZSH_CONFIG_ROOT="${HOME}/.dotfiles/zsh/conf.d"
ZSH_INCLDE_CONF=(
  base alias completion
  incremental
  python ruby perl node ssh golang
  envtool
  secret
)

# Function
# -------------------------------------
function __check_exist_and_source() {

  local target=$1
  [[ -f ${target}  ]] && source ${target}

}


# Main
# ------------------------------------------
### Added by Zplugin's installer
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin installer's chunk
source ${HOME}/.dotfiles/zsh/zplugin-conf.zsh

for conf in ${ZSH_INCLDE_CONF} ; do
  __check_exist_and_source ${ZSH_CONFIG_ROOT}/${conf}.zsh
done


export PATH="$HOME/.sc/bin:$PATH"
